name: Check Secret and Variable Access
description: Checks access to DEPLOY_TOKEN secret and DEPLOY_INFO variable

inputs:
  context-name:
    description: Name of the context where this is running (for logging)
    required: true

runs:
  using: composite
  steps:
    - name: Check secret and variable access
      shell: bash
      env:
        DEPLOY_TOKEN: ${{ env.DEPLOY_TOKEN }}
        DEPLOY_INFO: ${{ env.DEPLOY_INFO }}
      run: |
        echo "🔍 Checking access in: ${{ inputs.context-name }}"
        echo "================================"
        
        # Check DEPLOY_TOKEN secret
        if [ -z "$DEPLOY_TOKEN" ]; then
          echo "❌ DEPLOY_TOKEN secret is NOT accessible"
        else
          echo "✅ DEPLOY_TOKEN secret is accessible: ${DEPLOY_TOKEN:0:10}..."
        fi
        
        # Check DEPLOY_INFO variable
        if [ -z "$DEPLOY_INFO" ]; then
          echo "❌ DEPLOY_INFO variable is NOT accessible"
        else
          echo "✅ DEPLOY_INFO variable is accessible: $DEPLOY_INFO"
        fi
        
        echo "================================"
